api-key: './ddns-api-key.json'
logfile: './ddns.log'
hosts:
    -   host: 'subdomain.example.com.'
        project_id: 'example-123456'
        managed_zone: 'your-zone-name'
        domain: 'example.com'
        type: 'AAAA'
        ttl: 60
        interval: 600

    -   host: 'subdomain.example.com.'
        project_id: 'example-123456'
        managed_zone: 'your-zone-name'
        domain: 'example.com'
        type: 'AAAA'
        ttl: 60
        interval: 600
